# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BacteriaToolkit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1215, 730)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LaunchButton = QtWidgets.QPushButton(self.centralwidget)
        self.LaunchButton.setGeometry(QtCore.QRect(450, 160, 101, 31))
        self.LaunchButton.setObjectName("LaunchButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(55, 91, 71, 31))
        self.label.setObjectName("label")
        self.imgPathText = QtWidgets.QLineEdit(self.centralwidget)
        self.imgPathText.setGeometry(QtCore.QRect(160, 90, 111, 31))
        self.imgPathText.setObjectName("imgPathText")
        self.openImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.openImageButton.setGeometry(QtCore.QRect(290, 90, 101, 31))
        self.openImageButton.setObjectName("openImageButton")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(570, 20, 640, 480))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 220, 512, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.countLabel = QtWidgets.QLabel(self.centralwidget)
        self.countLabel.setGeometry(QtCore.QRect(360, 330, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.countLabel.setFont(font)
        self.countLabel.setText("")
        self.countLabel.setObjectName("countLabel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 180, 271, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.openImageDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.openImageDirButton.setGeometry(QtCore.QRect(420, 90, 131, 31))
        self.openImageDirButton.setObjectName("openImageDirButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "BacteriaToolkit"))
        self.LaunchButton.setText(_translate("mainWindow", "开始分析"))
        self.label.setText(_translate("mainWindow", "图片路径:"))
        self.openImageButton.setText(_translate("mainWindow", "选择图片"))
        self.openImageDirButton.setText(_translate("mainWindow", "选择图片(文件夹)"))
